on: pull_request
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-   
      - uses: actions/setup-java@v2
        with:
          java-version: "11"
          cache: "maven"
          distribution: "zulu"
          
      - run: mvn -B test
